### ISSUE TITLE
User Activity Still Visible

### ISSUE THREAD

**Issue by mrjarbenne** [r-a-y/bp-hide-user#1]
Although attempts to navigate to a hidden user result in a "user is restricted" notice, their subsite activity is still visible in the activity stream.

**Comment by r-a-y** [comment]
Right, the code only handles the Members Directory.

Shouldn't take too much effort to add support for the activity stream.

**Comment by mrjarbenne** [comment]
I'm seeing some odd behaviour now in the Personal Activity stream on a users profile. The full community stream is appearing in the Personal feed, rather than the individual user's content. Deactivating Hide Users rectifies the issue: 

![2015-12-02_20-40-54](https://cloud.githubusercontent.com/assets/480667/11549630/90661bc4-9935-11e5-8a5f-1dacc5cb558b.png)

**Comment by r-a-y** [comment]
I've limited the code to the Activity Directory page.  Let me know if this works.

**Comment by mrjarbenne** [comment]
That seems to have sorted it out.
